# Generated by Django 3.1.3 on 2020-11-08 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaProduto',
            fields=[
                ('id_media_produto', models.AutoField(db_column='id_media_produto', primary_key=True, serialize=False)),
                ('valor', models.DecimalField(db_column='valor', decimal_places=2, max_digits=18)),
                ('dt_media', models.DateTimeField(auto_now_add=True, db_column='dt_media')),
                ('tipo', models.CharField(blank=True, db_column='tipo', max_length=1, null=True)),
                ('id_produto', models.ForeignKey(db_column='id_produto_fk', on_delete=django.db.models.deletion.PROTECT, to='produtos.produtos')),
            ],
            options={
                'db_table': 'MediaProduto',
                'managed': True,
            },
        ),
    ]
